/**
 * Utility for interacting with local/remote LLM engine APIs (Ollama, LM Studio, etc.)
 * based on OpenAI-compatible or provider-specific endpoints.
 */

export interface LLMModel {
  id: string;
  name?: string;
  object?: string;
  owned_by?: string;
}

/**
 * Normalizes the base URL to ensure it has a protocol and correct slashes.
 */
function normalizeUrl(url: string): string {
  let normalized = url.trim();
  if (!/^https?:\/\//i.test(normalized)) {
    normalized = `http://${normalized}`;
  }
  // Ensure no trailing slashes that cause double slashes in concatenation
  return normalized.replace(/\/+$/, '');
}

/**
 * Safely parses JSON from a response, checking the content type first.
 */
async function safeJsonParse(response: Response): Promise<any> {
  const contentType = response.headers.get('content-type');
  if (!contentType || !contentType.includes('application/json')) {
    const text = await response.text();
    console.error('Expected JSON but received:', text.substring(0, 100));
    throw new Error('Server returned a non-JSON response. Ensure your backend is running correctly.');
  }
  
  try {
    return await response.json();
  } catch (e) {
    console.error('Failed to parse JSON response:', e);
    throw new Error('Invalid JSON received from server.');
  }
}

export async function testConnection(baseUrl: string): Promise<boolean> {
  const normalizedBase = normalizeUrl(baseUrl);
  
  try {
    // Try multiple common endpoints if the base one fails
    const endpoints = [
      `${normalizedBase}/models`, 
      `${normalizedBase}/v1/models`, 
      `${normalizedBase}/api/v1/models`,
      `${normalizedBase}/api/models`,
      normalizedBase // Just the base URL as a fallback
    ];
    
    for (const url of endpoints) {
      try {
        const response = await fetch(url, {
          method: 'GET',
          headers: { 'Accept': 'application/json' },
          mode: 'cors',
          signal: AbortSignal.timeout(5000)
        });
        
        // Even a 401 or 405 from some APIs means the server is reachable
        if (response.ok || response.status === 401 || response.status === 405) {
          return true;
        }
      } catch (e) {
        continue;
      }
    }
    return false;
  } catch (error) {
    console.error('Connection test failed:', error);
    return false;
  }
}

export async function fetchModels(baseUrl: string): Promise<LLMModel[]> {
  const normalizedBase = normalizeUrl(baseUrl);
  const endpoints = [
    `${normalizedBase}/models`, 
    `${normalizedBase}/v1/models`, 
    `${normalizedBase}/api/v1/models`,
    `${normalizedBase}/api/models`
  ];
  
  for (const url of endpoints) {
    try {
      const response = await fetch(url, {
        method: 'GET',
        headers: { 'Accept': 'application/json' },
        mode: 'cors',
        signal: AbortSignal.timeout(5000)
      });
      
      if (!response.ok) continue;
      
      const data = await safeJsonParse(response).catch(() => null);
      if (!data) continue;
      
      // Handle different formats
      // 1. OpenAI format: { data: [...] }
      if (data.data && Array.isArray(data.data)) {
        return data.data.map((m: any) => ({ id: m.id, name: m.id }));
      }
      // 2. Ollama format: { models: [...] }
      if (data.models && Array.isArray(data.models)) {
        return data.models.map((m: any) => ({ id: m.name, name: m.name }));
      }
      // 3. Raw array
      if (Array.isArray(data)) {
        return data.map((m: any) => ({ 
          id: typeof m === 'string' ? m : (m.id || m.name), 
          name: typeof m === 'string' ? m : (m.name || m.id) 
        }));
      }
    } catch (error) {
      console.error(`Failed to fetch models from ${url}:`, error);
    }
  }
  return [];
}

export async function callChatCompletion(baseUrl: string, modelId: string, messages: any[], settings: any) {
  const normalizedBase = normalizeUrl(baseUrl);
  
  // Normalize the endpoint path
  let chatUrl = `${normalizedBase}/chat/completions`;
  if (normalizedBase.includes('/v1')) {
    chatUrl = `${normalizedBase}/chat/completions`;
  } else if (!normalizedBase.includes('/api/')) {
    chatUrl = `${normalizedBase}/v1/chat/completions`;
  }

  try {
    const response = await fetch(chatUrl, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        model: modelId,
        messages,
        temperature: settings.temperature,
        top_p: settings.topP,
        max_tokens: settings.maxTokens,
        stream: false
      }),
      mode: 'cors'
    });

    if (!response.ok) {
      const errorData = await response.text().catch(() => 'Unknown server error');
      throw new Error(`Engine Error (${response.status}): ${errorData}`);
    }

    const data = await safeJsonParse(response);
    return data.choices?.[0]?.message?.content || "No response generated by the engine.";
  } catch (error: any) {
    console.error('Chat Completion failed:', error);
    throw error;
  }
}
